#!/usr/bin/env python3
"""
Convert 93x87 (4-col x 3-row) sprite sheets to 144x32 strip format.

Input format (93x87, roughly 23x29 per frame):
  - Row 0: facing DOWN (4 frames: idle, walk1, idle?, walk2)
  - Row 1: facing SIDEWAYS (appears to face LEFT, will verify)
  - Row 2: facing UP (4 frames)

Output format (144x32 strip, 16x32 per frame):
  - 9 frames: [D-idle][D-w1][D-w2][U-idle][U-w1][U-w2][L-idle][L-w1][L-w2]
  - RIGHT direction is generated by mirroring LEFT

Usage:
  python3 scripts/convert-sprite-sheet.py <input.png> <output.png>
  python3 scripts/convert-sprite-sheet.py uploads/grok-v2.png public/assets/sprites/grok.png
"""

import sys
from pathlib import Path
from PIL import Image

# Output dimensions
OUT_FRAME_W = 16
OUT_FRAME_H = 32
OUT_STRIP_W = 144  # 9 frames
OUT_STRIP_H = 32

# Input grid: 4 cols x 3 rows
IN_COLS = 4
IN_ROWS = 3


def get_bounding_box(img: Image.Image, x: int, y: int, w: int, h: int) -> tuple[int, int, int, int]:
    """Find the bounding box of non-transparent pixels in a region."""
    region = img.crop((x, y, x + w, y + h))
    if region.mode != 'RGBA':
        region = region.convert('RGBA')
    
    pixels = region.load()
    min_x, min_y = w, h
    max_x, max_y = 0, 0
    
    for py in range(h):
        for px in range(w):
            r, g, b, a = pixels[px, py]
            if a > 0:  # Non-transparent
                min_x = min(min_x, px)
                min_y = min(min_y, py)
                max_x = max(max_x, px)
                max_y = max(max_y, py)
    
    if max_x < min_x:  # Empty frame
        return (0, 0, w, h)
    
    return (min_x, min_y, max_x + 1, max_y + 1)


def extract_frame(img: Image.Image, col: int, row: int, cell_w: float, cell_h: float) -> Image.Image:
    """Extract a single frame from the input grid, centered in output cell."""
    x = int(col * cell_w)
    y = int(row * cell_h)
    w = int(cell_w)
    h = int(cell_h)
    
    # Handle edge cases for last column/row
    if col == IN_COLS - 1:
        w = img.width - x
    if row == IN_ROWS - 1:
        h = img.height - y
    
    # Get bounding box of actual sprite content
    bbox = get_bounding_box(img, x, y, w, h)
    bx, by, bx2, by2 = bbox
    content_w = bx2 - bx
    content_h = by2 - by
    
    # Extract content
    content = img.crop((x + bx, y + by, x + bx2, y + by2))
    
    # Create output frame
    out_frame = Image.new('RGBA', (OUT_FRAME_W, OUT_FRAME_H), (0, 0, 0, 0))
    
    # Center horizontally, align feet to bottom
    paste_x = (OUT_FRAME_W - content_w) // 2
    paste_y = OUT_FRAME_H - content_h  # Feet at bottom
    
    # Clamp to frame bounds
    paste_x = max(0, min(paste_x, OUT_FRAME_W - content_w))
    paste_y = max(0, min(paste_y, OUT_FRAME_H - content_h))
    
    out_frame.paste(content, (paste_x, paste_y))
    return out_frame


def convert_sheet(input_path: str, output_path: str, side_facing: str = 'left') -> None:
    """Convert a 93x87 grid to 144x32 strip."""
    img = Image.open(input_path).convert('RGBA')
    
    print(f"Input: {input_path} ({img.width}x{img.height})")
    
    cell_w = img.width / IN_COLS
    cell_h = img.height / IN_ROWS
    print(f"Cell size: {cell_w:.1f}x{cell_h:.1f}")
    
    # Create output strip
    out = Image.new('RGBA', (OUT_STRIP_W, OUT_STRIP_H), (0, 0, 0, 0))
    
    # Input rows: 0=down, 1=side, 2=up
    # Output columns: [D-idle][D-w1][D-w2][U-idle][U-w1][U-w2][L-idle][L-w1][L-w2]
    
    # Down row (input row 0): cols 0,1,3 -> output cols 0,1,2
    frame_d_idle = extract_frame(img, 0, 0, cell_w, cell_h)
    frame_d_walk1 = extract_frame(img, 1, 0, cell_w, cell_h)
    frame_d_walk2 = extract_frame(img, 3, 0, cell_w, cell_h)
    
    # Up row (input row 2): cols 0,1,3 -> output cols 3,4,5
    frame_u_idle = extract_frame(img, 0, 2, cell_w, cell_h)
    frame_u_walk1 = extract_frame(img, 1, 2, cell_w, cell_h)
    frame_u_walk2 = extract_frame(img, 3, 2, cell_w, cell_h)
    
    # Side row (input row 1): cols 0,1,3 -> output cols 6,7,8
    # If side_facing='left', these are the left-facing frames
    # If side_facing='right', we'll mirror them for left
    frame_s_idle = extract_frame(img, 0, 1, cell_w, cell_h)
    frame_s_walk1 = extract_frame(img, 1, 1, cell_w, cell_h)
    frame_s_walk2 = extract_frame(img, 3, 1, cell_w, cell_h)
    
    if side_facing == 'right':
        # Mirror to get left-facing
        frame_s_idle = frame_s_idle.transpose(Image.FLIP_LEFT_RIGHT)
        frame_s_walk1 = frame_s_walk1.transpose(Image.FLIP_LEFT_RIGHT)
        frame_s_walk2 = frame_s_walk2.transpose(Image.FLIP_LEFT_RIGHT)
    
    # Paste frames into strip
    out.paste(frame_d_idle, (0 * OUT_FRAME_W, 0))
    out.paste(frame_d_walk1, (1 * OUT_FRAME_W, 0))
    out.paste(frame_d_walk2, (2 * OUT_FRAME_W, 0))
    
    out.paste(frame_u_idle, (3 * OUT_FRAME_W, 0))
    out.paste(frame_u_walk1, (4 * OUT_FRAME_W, 0))
    out.paste(frame_u_walk2, (5 * OUT_FRAME_W, 0))
    
    out.paste(frame_s_idle, (6 * OUT_FRAME_W, 0))
    out.paste(frame_s_walk1, (7 * OUT_FRAME_W, 0))
    out.paste(frame_s_walk2, (8 * OUT_FRAME_W, 0))
    
    # Save output
    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    out.save(output_path)
    print(f"Output: {output_path} ({out.width}x{out.height})")


def main():
    if len(sys.argv) < 3:
        print(__doc__)
        sys.exit(1)
    
    input_path = sys.argv[1]
    output_path = sys.argv[2]
    side_facing = sys.argv[3] if len(sys.argv) > 3 else 'left'
    
    convert_sheet(input_path, output_path, side_facing)
    print("Done!")


if __name__ == '__main__':
    main()
