#!/usr/bin/env python3
"""
Convert 128x192 (4-col x 4-row, 32x48 per frame) RPG-style sprite sheets to 144x32 strip format.

Input format (128x192, 32x48 per frame):
  - Row 0: facing DOWN
  - Row 1: facing LEFT
  - Row 2: facing RIGHT
  - Row 3: facing UP
  - Column layout varies, but typically:
    - Col 0: walk frame 1
    - Col 1: idle/standing frame
    - Col 2: walk frame 2
    - Col 3: idle/standing frame (often duplicate of col 1)

Output format (144x32 strip, 16x32 per frame):
  - 9 frames: [D-idle][D-w1][D-w2][U-idle][U-w1][U-w2][L-idle][L-w1][L-w2]
  - RIGHT direction is generated by mirroring LEFT at runtime

Usage:
  python3 scripts/convert-rpg-sheet.py <input.png> <output.png> [--idle-col N]
  
Examples:
  # Standard RPG Maker layout: idle in column 1
  python3 scripts/convert-rpg-sheet.py sheets/jarvis.png sprites/jarvis.png
  
  # Custom layout: idle in column 0
  python3 scripts/convert-rpg-sheet.py sheets/custom.png sprites/custom.png --idle-col 0
"""

import sys
import argparse
from pathlib import Path
from PIL import Image

# Output dimensions
OUT_FRAME_W = 16
OUT_FRAME_H = 32
OUT_STRIP_W = 144  # 9 frames
OUT_STRIP_H = 32

# Input grid: 4 cols x 4 rows, 32x48 per frame
IN_COLS = 4
IN_ROWS = 4
IN_FRAME_W = 32
IN_FRAME_H = 48


def get_bounding_box(img: Image.Image, x: int, y: int, w: int, h: int) -> tuple[int, int, int, int]:
    """Find the bounding box of non-transparent pixels in a region."""
    region = img.crop((x, y, x + w, y + h))
    if region.mode != 'RGBA':
        region = region.convert('RGBA')
    
    pixels = region.load()
    min_x, min_y = w, h
    max_x, max_y = 0, 0
    
    for py in range(h):
        for px in range(w):
            r, g, b, a = pixels[px, py]
            if a > 0:
                min_x = min(min_x, px)
                min_y = min(min_y, py)
                max_x = max(max_x, px)
                max_y = max(max_y, py)
    
    if max_x < min_x:
        return (0, 0, w, h)
    
    return (min_x, min_y, max_x + 1, max_y + 1)


def extract_frame(img: Image.Image, col: int, row: int) -> Image.Image:
    """Extract a single frame from the input grid, scaled and centered in output cell."""
    x = col * IN_FRAME_W
    y = row * IN_FRAME_H
    
    # Get bounding box of actual sprite content
    bbox = get_bounding_box(img, x, y, IN_FRAME_W, IN_FRAME_H)
    bx, by, bx2, by2 = bbox
    content_w = bx2 - bx
    content_h = by2 - by
    
    # Extract content
    content = img.crop((x + bx, y + by, x + bx2, y + by2))
    
    # Scale to fit in output frame while maintaining aspect ratio
    # Target is roughly 14 pixels wide to leave 1px margin on each side
    scale = min(14 / content_w, (OUT_FRAME_H - 2) / content_h) if content_w > 0 and content_h > 0 else 1
    new_w = max(1, int(content_w * scale))
    new_h = max(1, int(content_h * scale))
    
    content = content.resize((new_w, new_h), Image.NEAREST)
    
    # Create output frame
    out_frame = Image.new('RGBA', (OUT_FRAME_W, OUT_FRAME_H), (0, 0, 0, 0))
    
    # Center horizontally, align feet to bottom
    paste_x = (OUT_FRAME_W - new_w) // 2
    paste_y = OUT_FRAME_H - new_h
    
    out_frame.paste(content, (paste_x, paste_y))
    return out_frame


def get_walk_cols(idle_col: int) -> tuple[int, int]:
    """Get walk frame columns based on idle column position."""
    available = [c for c in range(4) if c != idle_col and c != 3]  # Skip col 3 (usually duplicate)
    if len(available) < 2:
        available = [c for c in range(4) if c != idle_col]
    return (available[0], available[1] if len(available) > 1 else available[0])


def convert_sheet(input_path: str, output_path: str, idle_col: int = 1) -> None:
    """Convert a 128x192 grid to 144x32 strip."""
    img = Image.open(input_path).convert('RGBA')
    
    print(f"Input: {input_path} ({img.width}x{img.height})")
    
    # Verify dimensions
    expected_w, expected_h = IN_COLS * IN_FRAME_W, IN_ROWS * IN_FRAME_H
    if img.width != expected_w or img.height != expected_h:
        print(f"Warning: Expected {expected_w}x{expected_h}, got {img.width}x{img.height}")
    
    # Get walk columns
    walk1_col, walk2_col = get_walk_cols(idle_col)
    print(f"Frame mapping: idle={idle_col}, walk1={walk1_col}, walk2={walk2_col}")
    
    # Create output strip
    out = Image.new('RGBA', (OUT_STRIP_W, OUT_STRIP_H), (0, 0, 0, 0))
    
    # Input rows: 0=down, 1=left, 2=right (ignored, mirror left), 3=up
    # Output columns: [D-idle][D-w1][D-w2][U-idle][U-w1][U-w2][L-idle][L-w1][L-w2]
    
    # Down (input row 0)
    out.paste(extract_frame(img, idle_col, 0), (0 * OUT_FRAME_W, 0))
    out.paste(extract_frame(img, walk1_col, 0), (1 * OUT_FRAME_W, 0))
    out.paste(extract_frame(img, walk2_col, 0), (2 * OUT_FRAME_W, 0))
    
    # Up (input row 3)
    out.paste(extract_frame(img, idle_col, 3), (3 * OUT_FRAME_W, 0))
    out.paste(extract_frame(img, walk1_col, 3), (4 * OUT_FRAME_W, 0))
    out.paste(extract_frame(img, walk2_col, 3), (5 * OUT_FRAME_W, 0))
    
    # Left (input row 1)
    out.paste(extract_frame(img, idle_col, 1), (6 * OUT_FRAME_W, 0))
    out.paste(extract_frame(img, walk1_col, 1), (7 * OUT_FRAME_W, 0))
    out.paste(extract_frame(img, walk2_col, 1), (8 * OUT_FRAME_W, 0))
    
    # Save output
    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    out.save(output_path)
    print(f"Output: {output_path} ({out.width}x{out.height})")


def main():
    parser = argparse.ArgumentParser(
        description='Convert 128x192 RPG sprite sheets to 144x32 strip format',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__
    )
    parser.add_argument('input', help='Input sprite sheet (128x192 PNG)')
    parser.add_argument('output', help='Output strip (144x32 PNG)')
    parser.add_argument('--idle-col', type=int, default=1, choices=[0, 1, 2, 3],
                        help='Column index of idle frame (default: 1 for RPG Maker style)')
    
    args = parser.parse_args()
    convert_sheet(args.input, args.output, args.idle_col)
    print("Done!")


if __name__ == '__main__':
    main()
